import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GoogleOAuthProviders } from "@/providers/GoogleOAuthProviders";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";
import { QueryClientProviders } from "@/providers/QueryClientProviders";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientProviders>

            <GoogleOAuthProviders>
              {children}
              <Toaster />
            </GoogleOAuthProviders>
          </QueryClientProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
